### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by iceman3k** [openaiken/cloudflare-zerotrust-dns-updater#1]
Permissions for an API token with "Account: Zero Trust: Edit" permissions results in the following error:
`{"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}`

I have tried numerous API permissions and cannot find the correct combination. Using the standard API call with added X-Auth-Key only works with the Global API key:
curl --request PUT \
  --url https://api.cloudflare.com/client/v4/accounts/identifier/gateway/locations/uuid \
  --header 'Content-Type: application/json' \
  --header 'X-Auth-Email: ' \
  --header 'X-Auth-Key: ' \
  --data '{
  "client_default": false,
  "ecs_support": false,
  "name": "Austin Office Location",
  "networks": [
    {
      "network": "192.0.2.1/32"
    }
  ]
}'

**Comment by openaiken** [comment]
Thanks for opening the first issue! It makes me happy that someone actually found this little repo.

I might be able to help, but I might need to ask more questions about your usage. Were you running my script or executing curl commands yourself?
- If it was my script can you provide the full ERROR message?
- Or, if you're running raw curl commands, you will need to use a different header than Email/Key. If you look at the source, I'm using the Authorization header: `--header "Authorization: Bearer $token" \
`
An Auth Token is different than an API Key so you have to set up the headers differently. but you set up the permissions correctly. My token's only permission is the one you mentioned.

Since you pasted the example from the documentation it seems, I'm not sure what else may be right or wrong for you.

**Comment by iceman3k** [comment]
I am happy to have found your little corner! It seems like most of the internet does not have an automatic solution to update the DNS location IP when a dynamic IP is in use. 

I was using the API command that I pasted above. I did create an API token with the "Account: Zero Trust: Edit" permissions. It seems that I am missing the concept of a Bearer. 

> (After posting this reply to you, I am adding this, I changed from using single quotes to double quotes with your authorization header, that worked. I had to refresh my knowledge, single quotes won't interpolate anything, but double quotes will.)


So I ran your script, and it ran successfully. I had to install jq as you instruct. But I will mention your script was only successful after I disabled proxy mode. With proxy mode enabled, I was getting whatever random IP Cloudflare assigned to it.

I originally found your script trying to find a way to modify this DDNS worker script. https://github.com/workerforce/unifi-ddns. It is for Unifi firewalls and updating Cloudflare DNS Zones using its DDNS function (DynDNS). This worker script updates the domain or subdomain with your dynamic IP, and allows for proxy mode to be active. The following is what I had come up, with the the help of Google's Bard. I added this in at line 164 on the worker script. I tried to grab the variables previous used. The token is used as the "Password" on the Unifi device and passed to the worker script. I would have liked to incorporate a function like you did that grabbed the account ID and uuid of the DNS location. My coding skills are terrible at best. I was not getting any logs back via the Cloudflare web interface, so I had decided to use the plain API to see if my permissions were at least correct. (The Code brackets aren't working with this)

< async function informZeroTrust(hostnames, ip, name, token) {

	  // Update Zero Trust Gateway location after updating DNS records
	  try {
	    const cloudflare = new Cloudflare({ token });
	    const locationId = "Location_ID"; // Replace with the actual location ID
	    const accountID = "Account_ID"; // Replace with the actual Account ID
	    const response = await fetch(`https://api.cloudflare.com/client/v4/accounts/${accountId}/gateway/locations/${locationId}`, 
             {
	      method: "PUT",
	      headers: {
	        "Content-Type": "application/json",
	        Authorization: `Bearer ${token}`,
	      },
	      body: JSON.stringify({
	        name: "Name_Of_Location",  // Ensure this matches the DNS Location name
	        ecs_support: true,
	        networks: [ip],       // Update with the new IP address
	        client_default: true, // Adjust as needed
	      }),
	    });

	    if (!response.ok) {
	      throw new Error(`Failed to update Zero Trust Gateway location: ${response.statusText}`);
	    }

	    console.log("Zero Trust Gateway location updated successfully.");
	  } catch (error) {
	    console.error("Error updating Zero Trust Gateway location:", error);
	    // Handle error gracefully, e.g., log it or send a notification
	  }

	  return new Response("good", {
	    status: 200,
	    headers: {
	      "Content-Type": "text/plain;charset=UTF-8",
	      "Cache-Control": "no-store",
	    },
	});
}
>
I realize this differs greatly from your script. Apologies. But as far as 'Issues' go with your script, the Issue I can comment on would it does not work with a proxied A Record. 

Thank you for your initial reply!

**Comment by openaiken** [comment]
Yep, that makes perfect sense. When you enable proxy mode for a record, CF will redirect traffic instead of pointing directly to you, instead of advertising your actual WAN address. All this means is that you would have to get the WAN Address via a method other than `dig`ging the A record. That is very context dependent. You could query the router directly (e.g. SNMPv3 or a REST API depending on the vendor, etc.), or you could (especially in the example of a home network like mine) use another external tool such as https://ifconfig.me. Running `curl ifconfig.me` would return the external address you're connecting from, and that value can facilitate better use of this updater bash script.

I'm not sure I'd want to bake in use of a random 3rd party site like that, but it would be a very easy source modification -- just rewrite `get_current_wan_address()`.

**Comment by openaiken** [comment]
I edited the Readme with a note regarding this discussion (a468dbd). I welcome any other feedback or questions I may be able to help with. otherwise you might close this issue at your leisure. :)
